// Sputnik Engine resource header file
// This file is autogenerated

extern unsigned char res_logopng[];
extern int res_logopng_size;

extern unsigned char res_spritepng[];
extern int res_spritepng_size;

extern unsigned char res_testogg[];
extern int res_testogg_size;

extern unsigned char res_tilespng[];
extern int res_tilespng_size;

